# Generated by Django 4.0.4 on 2022-04-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=255)),
                ('product_title', models.CharField(max_length=255)),
                ('product_image', models.ImageField(upload_to='image/product/')),
                ('product_price', models.FloatField()),
                ('product_credit_price', models.FloatField()),
                ('short_description', models.TextField()),
                ('deep_description', models.TextField()),
                ('characteristics', models.JSONField()),
                ('comment', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Example',
        ),
    ]
