# Generated by Django 4.0.4 on 2022-04-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_product_delete_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.JSONField(default='{}'),
        ),
    ]
