# Generated by Django 4.0.4 on 2022-04-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0005_alter_product_characteristics_alter_product_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_title',
            new_name='product_model_name',
        ),
    ]
