# Generated by Django 4.0.4 on 2022-04-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0006_rename_product_title_product_product_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url_name',
        ),
    ]
