# Generated by Django 4.0.4 on 2022-04-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0007_remove_product_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='modelapp/static/image/product/'),
        ),
    ]
