# Generated by Django 4.0.4 on 2022-04-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelapp', '0002_product_delete_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100)),
                ('category_credit_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_credit_price', to='modelapp.product')),
                ('category_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_price', to='modelapp.product')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_image', to='modelapp.product')),
                ('product_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_title', to='modelapp.product')),
            ],
        ),
    ]
