# Generated by Django 4.0.4 on 2022-04-29 09:58

import categoris.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/category/')),
                ('cat_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1_image', models.ImageField(upload_to='image/subcategory1/')),
                ('subcategory1_name', models.CharField(max_length=200)),
                ('sub1_title', models.ForeignKey(null=True, on_delete=categoris.models.Category, related_name='cats_title', to='categoris.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
