# Generated by Django 4.0.4 on 2022-04-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoris', '0002_category_subcategory1_delete_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_title',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='modelapp/static/image/category/'),
        ),
        migrations.AlterField(
            model_name='subcategory1',
            name='sub1_image',
            field=models.ImageField(upload_to='modelapp/static/image/subcategory1/'),
        ),
    ]
