# Generated by Django 4.0.4 on 2022-04-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoris', '0003_alter_category_cat_title_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
