# Generated by Django 4.0.4 on 2022-04-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoris', '0004_alter_category_cat_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('product_model_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(upload_to='modelapp/static/image/product/')),
                ('product_price', models.FloatField()),
                ('product_credit_price', models.FloatField()),
                ('short_description', models.TextField()),
                ('deep_description', models.TextField()),
                ('characteristics', models.JSONField(default=dict)),
                ('comment', models.JSONField(default=dict)),
            ],
        ),
    ]
