# Generated by Django 4.0.4 on 2022-04-30 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoris', '0006_alter_subcategory1_sub1_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory2',
            name='product_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory1s_name', to='categoris.subcategory1'),
        ),
    ]
