# Generated by Django 4.0.4 on 2022-07-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoris', '0007_alter_subcategory2_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory2',
            name='product_color',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Gray', 'Gray'), ('Black', 'Black'), ('Green', 'Green')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='subcategory2',
            name='product_old_price',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory2',
            name='product_price',
            field=models.CharField(max_length=200),
        ),
    ]
