# Generated by Django 4.0.4 on 2022-07-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoris', '0008_subcategory2_product_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('insta_link', models.CharField(max_length=255)),
                ('telegram_link', models.CharField(max_length=255)),
                ('facebock_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('new_image', models.ImageField(upload_to='modelapp/static/image/new/')),
                ('crete_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
